apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobentry
  labels:
    app: jobentry
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jobentry
  template:
    metadata:
      labels:
        app: jobentry
    spec:
      containers:
        - name: jobentry
          image: 637423529262.dkr.ecr.us-east-1.amazonaws.com/jobentry:v1.0.0
          ports:
            - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: jobentry-service
spec:
  selector:
    app: jobentry
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
